- src/__tests__/evaluate.test.ts
- src/__tests__/logger.test.ts
- src/__tests__/prefab.test.ts
- src/__tests__/testHelpers.ts
- src/logger.ts
- src/prefab.ts
- src/resolver.ts
- Stronger typings
- Move log level string -> log level number coercion to boundary
- Fix issue with defaultLogLevel not being respected
> refactor: shouldLog interface

- src/__tests__/telemetry/contextShapes.test.ts
- src/__tests__/telemetry/knownLoggers.test.ts
- src/__tests__/testHelpers.ts
- src/apiClient.ts
- src/parseProto.ts
- src/prefab.ts
- src/resolver.ts
- src/telemetry/contextShapes.ts
- src/telemetry/knownLoggers.ts
- src/telemetry/reporter.ts
- src/telemetry/types.ts
- src/types.ts
Not enabled by default, but you can opt-in with `contextUploadMode:
"shapeOnly"`
This telemetry data is used to populate the property dropdown in the
Prefab rule builder.
> Telemetry: Context shape reporting

- src/__tests__/evaluate.test.ts
- src/__tests__/integration.test.ts
- src/__tests__/integrationHelper.ts
- src/__tests__/prefab.test.ts
- src/__tests__/telemetry/contextShapes.test.ts
- src/__tests__/telemetry/exampleContexts.test.ts
- src/__tests__/telemetry/rateLimitCache.test.ts
- src/__tests__/wrap.test.ts
- src/prefab.ts
- src/resolver.ts
- src/telemetry/exampleContexts.ts
- src/telemetry/rateLimitCache.ts
- src/wrap.ts
Enabled by default, but you can opt-out by setting `contextUploadMode`
to `shapeOnly` or `none`.
This telemetry data is used to populate the Contexts section of the
Prefab UI where you can easily override variants for your users.
> Telemetry: Example Contexts reporting

- package.json
- src/__tests__/evaluate.test.ts
- src/__tests__/fixtures/basicConfig.ts
- src/__tests__/fixtures/basicLogLevel.ts
- src/__tests__/fixtures/propIsOneOf.ts
- src/__tests__/integration.test.ts
- src/__tests__/integrationHelper.ts
- src/__tests__/telemetry/evaluationSummaries.test.ts
- src/__tests__/telemetry/exampleContexts.test.ts
- src/__tests__/unwrap.test.ts
- src/evaluate.ts
- src/prefab.ts
- src/resolver.ts
- src/telemetry/evaluationSummaries.ts
- src/unwrap.ts
Enabled by default, this sends data to Prefab about how frequently a
config/flag is serving a particular value.
This powers the evaluation metrics/charts in the Prefab UI.
You can disable it by setting `collectEvaluationSummaries: false` in the
options.
> Telemetry: Evaluation summary reporting

- src/__tests__/evaluate.test.ts
- src/__tests__/fixtures/propIsOneOf.ts
- src/__tests__/prefab.test.ts
- src/__tests__/telemetry/contextShapes.test.ts
- src/__tests__/telemetry/evaluationSummaries.test.ts
- src/__tests__/telemetry/exampleContexts.test.ts
- src/loadConfig.ts
- src/prefab.ts
- src/proto.json
- src/proto.ts
- src/resolver.ts
- onUpdate can be used to take action when config changes.
- default context allows for per-api-key/user overrides
> onUpdate and default context

- src/__tests__/encryption.test.ts
- src/__tests__/evaluate.test.ts
- src/__tests__/fixtures/decryptionKeyConfig.ts
- src/__tests__/fixtures/propDoesNotEndWithOneOf.ts
- src/__tests__/fixtures/propEndsWithOneOf.ts
- src/__tests__/fixtures/propIsNotOneOf.ts
- src/__tests__/fixtures/propIsOneOf.ts
- src/__tests__/fixtures/propIsOneOfAndEndsWith.ts
- src/__tests__/fixtures/secretConfig.ts
- src/__tests__/logger.test.ts
- src/__tests__/prefab.test.ts
- src/__tests__/unwrap.test.ts
- src/encryption.ts
- src/evaluate.ts
- src/types.ts
- src/unwrap.ts
This also corrects some `valueType` values in test data that didn't
matter until now.
> feat(Secrets): Support encrypted secrets

- README.md
- src/__tests__/prefab.test.ts
- src/logger.ts
- src/mergeContexts.ts
- src/prefab.ts
- src/resolver.ts
- src/types.ts
e.g.
```javascript
{ user: { country: "US", "user-id": "5" } }
```
is valid context now. This can save a developer from having to Map-ify
things on their end.
> feat(Context): Accept objects for context

- src/__tests__/prefab.test.ts
- src/evaluate.ts
- src/prefab.ts
- src/resolver.ts
- src/telemetry/evaluationSummaries.ts
- src/unwrap.ts
- src/wrap.ts
This allows for setting run-time config. This is especially useful for
setting `prefab.secrets.encryption.key` at run-time.
example:
```javascript
// pass a config key string and a ConfigValue pair
prefab.set("prefab.secrets.encryption.key", { string: decryptionKey })
```
You can also pass config in to `prefab.init()` as an array of
key/ConfigValue pairs.
Example:
```javascript
prefab.init([
["some.number", { int: new Long(19) }],
["hello", { string: "world" }],
]);
```
> Feat: Allow prefab.set (experimental)

- src/__tests__/prefab.test.ts
- src/prefab.ts
Exposes `.updateNow()` to give the user control over update scheduling
(versus polling, SSE, etc.)
> feat: updateNow

- src/__tests__/prefab.test.ts
- src/logger.ts
- src/prefab.ts
`.logger` takes a logger name and desiredLevel (optional if set at the
Prefab instance-level) and returns an object with the following methods:
- trace
- debug
- info
- warn
- error
- fatal
Example usage:
```typescript
const logger = prefab.logger("netlify.functions.example", "info");
logger.debug("This will not up") // does not log
logger.info("This will show up") // logs INFO  netlify.functions.example: This will show up
logger.error("This will show up") // logs ERROR netlify.functions.example: This will show up
```
> feat: .logger

- src/__tests__/prefab.test.ts
- src/logger.ts
- src/prefab.ts
- src/resolver.ts
You have two ways to use context with logger():
- Approach 1: If you initialize it from the inContext-provided variable, you'll get
a context-bound logger.
- Approach 2: When initializing on your Prefab instance, you can provide
context.
Approach 1 Example:
```typescript
const result = prefab.inContext({ user: { country: "US" } }, (pf) => {
// we initialize inside the context
const logger = pf.logger(loggerName, "info");
// these calls are bound to the inContext context so they'll evaluate
// with user.country of "US"
logger.debug("test")
// You can initialize a logger with JIT context if you desire
const jitLogger = pf.logger(loggerName, "info", { user: { country: "FR" } });
jitLogger.debug("test")
})
```
Approach 2 Example:
```typescript
const logger = prefab.logger(loggerName, …
```
> feat: logger() should inherit context

- .eslintrc.cjs
- src/__tests__/prefab.test.ts
- src/prefab.ts
Provide a convenience function for throttling `updateNow` calls based on
a duration in milliseconds. The update is only called if the duration
has passed since the last update was initialized.
e.g. You can call the following in a tight loop and be ensured that
it'll only update if the duration has passed.
```
prefab.updateIfStalerThan(1000); // if stale, update is triggered
prefab.updateIfStalerThan(1000); // since update is already scheduled, this won't fire
prefab.updateIfStalerThan(1000); // ditto
prefab.updateIfStalerThan(1000); // ditto
prefab.updateIfStalerThan(1000); // ditto
prefab.updateIfStalerThan(1000); // ditto
```
> feat: updateIfStalerThan

- CHANGELOG.md
- src/__tests__/integration.test.ts
- src/__tests__/integrationHelper.ts
- src/telemetry/exampleContexts.ts
- src/unwrap.ts
Changes:
- Don't report empty contexts with empty keys.
- Throw if required environment variable is absent.
- Throw if we can't parse an environment variable correctly.
> chore: update integration tests to latest

- CHANGELOG.md
- src/__tests__/telemetry/contextShapes.test.ts
- src/telemetry/contextShapes.ts
In the future, this might be served by periodicExample at the telemetry API-level, but right now we want to send both.
> fix: send context shapes by default

- src/__tests__/fixtures/mostlyDeletedConfig.ts
- src/__tests__/prefab.test.ts
- src/resolver.ts
An in-memory config should be removed when we receive a deleted config
over SSE.
> Config deletion fix

- src/__tests__/apiClient.test.ts
- src/apiClient.ts
- src/loadConfig.ts
- src/prefab.ts
This changes two things to lower the number of bytes our infra needs to serve
1) Keeps track of startAtId and uses that to fetch configuration data in polling mode rather than always using zero
2) Adds a caching wrapper around api client that supports some basic http cache-control header values. This allows us to hide the 304 no-data responses from the core client by serving it up some cached data rather than modifying it to cope with an up-to-date indication
Unit tests on cache implementation
Integration tests also exercise the caching
> More efficient config data fetching

- src/__tests__/prefab.test.ts
- src/prefab.ts
- src/resolver.ts
Compare `inContext` which evaluates a function in a context.
> Add `withContext` to get a context-bound resolver

- .github/workflows/test.yaml
- .gitignore
- src/__tests__/prefab.test.ts
- src/prefab.ts
- src/telemetry/reporter.ts
Telemetry timeouts kept prefab running such that you'd need to manually
`process.exit()` to close your script.
- CI
- Tested locally with a script similar to the one now in CI
> fix: Telemetry hanging after `prefab.close()`

- src/__tests__/contextLookup.test.ts
- src/contextLookup.ts
- src/evaluate.ts
implements prefab.current-time lookup for all operators -- it had previously only worked for IN_INT_RANGE
*(Outline the steps needed to be taken to verify the changes.)*
*(Optional section: Provide rollout and rollback procedures, when outside the bounds or requiring additional work beyond standard deployment)*
> implements prefab.current-time lookup for all operators

- README.md
- package-lock.json
- package.json
- src/__tests__/prefab.test.ts
- src/loadConfig.ts
- src/telemetry/knownLoggers.ts
- tsconfig.json
This avoids issues with Longs in protos being parsed as numbers on
Heroku w/ pnpm.
If we determine a long has been parsed as a number, we'll error and
tell the user we depend on `long`.
Also fix some linting errors.
- Manual testing
> Declare `long` as a peer dependency

- CHANGELOG.md
- package-lock.json
- package.json
- src/__tests__/contextLookup.test.ts
- src/evaluate.ts
changelog and version bumps for next release
> Release v0.4.8

- src/prefab.ts
This is a followup to #104 to correct the initial behavior: onUpdate was no longer being called after the first config load
> Fix: call onUpdate on initial load
