src/__tests__/integration.test.ts
src/__tests__/integrationHelper.ts
src/unwrap.ts

- Refactor integration tests for readability
- Add resolving for logLevel and double

Update integration tests for 0.2.1

---

package-lock.json
package.json
src/loadConfig.ts
src/prefab.ts

Support custom fetch

---

src/__tests__/evaluate.test.ts
src/__tests__/fixtures/basicLogLevel.ts
src/__tests__/integrationHelper.ts
src/__tests__/logger.test.ts
src/evaluate.ts
src/logger.ts
src/prefab.ts
src/proto.json
src/proto.ts
src/resolver.ts

Dynamic log levels via shouldLog

---

src/__tests__/logger.test.ts
src/logger.ts
src/prefab.ts
src/resolver.ts

TODO: make these level strings typescript/autocomplete friendly

Allow for string levels

---

src/loadConfig.ts
src/prefab.ts
src/types.ts

We need `status` and `arrayBuffer` at minimum

Be more specific about minimum fetch response

---

src/apiClient.ts
src/loadConfig.ts
src/makeHeaders.ts
src/prefab.ts
src/sseConnection.ts
src/types.ts

We'll use this for telemetry as well.

Introduce apiClient

---

src/__tests__/telemetry/exampleContexts.test.ts
src/__tests__/wrap.test.ts
src/wrap.ts

This matters for exampleContexts

Fix stringList wrapping

---

src/__tests__/telemetry/contextShapes.test.ts
src/__tests__/telemetry/evaluationSummaries.test.ts
src/__tests__/telemetry/exampleContexts.test.ts
src/__tests__/telemetry/knownLoggers.test.ts
src/telemetry/contextShapes.ts
src/telemetry/evaluationSummaries.ts
src/telemetry/exampleContexts.ts
src/telemetry/knownLoggers.ts

Prevent these from growing unbounded.

Telemetry: Set max data sizes for telemetry

---

README.md

This is actively used in prod now

Remove disclaimer.

---

.github/workflows/test.yaml
package.json
src/parseProto.ts
src/proto.json
src/proto.ts

Node (using vanilla JS, no bundler) wants file extensions here.
This also updates the proto.
https://github.com/stephenh/ts-proto#esm

ESM compatibility

---

README.md
src/__tests__/prefab.test.ts
src/prefab.ts
src/resolver.ts

- Fix context link and docs
- Expose `raw` and `keys` for introspection

Expose some internals and update docs

---

src/prefab.ts

fix(Context): defaultContext can only return Contexts

---

src/__tests__/prefab.test.ts
src/prefab.ts

This should help with mental modeling and avoiding an anti-pattern.

chore(init): Warn when called multiple times

---

src/__tests__/evaluate.test.ts
src/__tests__/fixtures/propIsOneOf.ts
src/__tests__/fixtures/secretKeyConfig.ts
src/__tests__/telemetry/evaluationSummaries.test.ts
src/__tests__/unwrap.test.ts
src/evaluate.ts
src/loadConfig.ts
src/telemetry/evaluationSummaries.ts
src/unwrap.ts

Report `*****` + the last 5 characters of the md5 hash.

feat: Do not report secrets/confidential values

---

src/__tests__/prefab.test.ts
src/prefab.ts
src/resolver.ts

Merging contexts on polling could throw an error
Also adds `.stopPolling`

fix: Polling bug

---

src/__tests__/integration.test.ts
src/__tests__/prefab.test.ts

chore: Disable telemetry in some tests

---

CHANGELOG.md
src/__tests__/evaluate.test.ts
src/__tests__/logger.test.ts
src/__tests__/prefab.test.ts
src/__tests__/telemetry/evaluationSummaries.test.ts
src/prefab.ts
src/resolver.ts

Update to #60 
Also updates how #53 is used

fix: Support updateIfStalerThan in inContext

---

src/__tests__/evaluate.test.ts
src/__tests__/fixtures/timedLogLevel.ts
src/__tests__/telemetry/exampleContexts.test.ts
src/evaluate.ts
src/telemetry/evaluationSummaries.ts
src/telemetry/exampleContexts.ts
src/telemetry/knownLoggers.ts

This brings support for timed logger

feat: Support IN_INT_RANGE

---

CHANGELOG.md
src/__tests__/duration.test.ts
src/__tests__/integrationHelper.ts
src/duration.ts
src/proto.json
src/proto.ts
src/unwrap.ts

This returns a duration in miliseconds

Add duration support

---

package-lock.json

- `@babel/traverse`
- protobufjs

Upgrade deps for security

---

CHANGELOG.md
package-lock.json
src/__tests__/integration.test.ts
src/__tests__/integrationHelper.ts
src/__tests__/unwrap.test.ts
src/prefab.ts
src/proto.json
src/proto.ts
src/resolver.ts
src/unwrap.ts

- **Upgrade to new eval summary integration data format**
- **Handle JSON values**
- **Support global contexts**

Support JSON configs and global context

---

src/__tests__/integration.test.ts
src/__tests__/prefab.test.ts
src/__tests__/telemetry/contextShapes.test.ts
src/__tests__/telemetry/evaluationSummaries.test.ts
src/__tests__/telemetry/exampleContexts.test.ts
src/__tests__/telemetry/knownLoggers.test.ts
src/apiClient.ts
src/evaluate.ts
src/loadConfig.ts
src/prefab.ts
src/sources.ts
src/sseConnection.ts
src/telemetry/contextShapes.ts
src/telemetry/evaluationSummaries.ts
src/telemetry/exampleContexts.ts
src/telemetry/knownLoggers.ts

Use belt and suspenders

---

src/sources.ts

Allow telemetry when using api source directly

---

src/__tests__/evaluate.test.ts
src/__tests__/fixtures/propAfter.ts
src/__tests__/fixtures/propBefore.ts
src/evaluate.ts
src/unwrap.ts

@semanticart what do you think of the changes to unwrap here? it was only returning the lower 32 bits of timestamps

Add before and after date ops

---

src/evaluate.ts

This builds on earlier PR to remove an error prone switch statement fall through by passing in the evaluation method to use. 
unit tests
n/a

pass long comparison method to remove switch statement fall through

---

src/__tests__/evaluate.test.ts
src/__tests__/fixtures/propRegexMatches.ts
src/evaluate.ts

adds regex matching operator
unit tests
n/a

adds regex matching operator

---

src/__tests__/integration.test.ts
src/prefab.ts
src/sseConnection.ts

This adds a close method to shut down some internal resources in order to prevent hanging. Fixes https://github.com/prefab-cloud/prefab-cloud-node/issues/81
unable to reproduce the hang locally; calling close in the integration test isn't causing any problems

Adds a close method to prefab to prevent hanging on shutdown

---

src/__tests__/evaluate.test.ts
src/__tests__/fixtures/propSemverMatches.ts
src/__tests__/semanticversion.test.ts
src/evaluate.ts
src/semanticversion.ts

Add Semantic Version (SemVer) comparison operators
Unit tests
n/a

Add Semantic Version (SemVer) comparison operators

---

CHANGELOG.md
package-lock.json
package.json

Ready for next release

---

src/proto.json
src/proto.ts

Updates to a version of the public protos with schema type and links.

updated protos with schema types

---

package-lock.json
package.json

create a pre-release to test the onChange listener functionality

release 0.4.9-pre.0
